server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8

app:
  auth: duan
  name: spring-boot-common-demo
  enable: true

# mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: ABC246810
    type: com.alibaba.druid.pool.DruidDataSource
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    password:
    port: 6379