

rocketmq:
  nameSrv:
    address: 120.79.128.250:9876
  producer:
    group:
      test: rkmq-pro-group-one
  consumer:
    group:
      test: rkmq-con-group-test
  topic:
    test: rkmq-topic-test
  tag:
    test: rkmq-tag-test
