

server:
  tomcat:
    uri-encoding: utf-8

# mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: ABC246810
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true